_target_: grinch.GRPipeline.Config

data_readpath: data/Psoriasis_gse171012.h5ad
data_writepath: data/Psoriasis_gse171012_pca20.h5ad

processors:
  - _target_: grinch.GeneIdToName.Config
  - _target_: grinch.PCA.Config
    n_components: 20
  - _target_: grinch.UMAP.Config
  - _target_: grinch.FuzzySimplicialSetGraph.Config
    n_neighbors: 5
  - _target_: grinch.Leiden.Config
    resolution: 0.9
  - _target_: grinch.KSTest.Config
    group_key: obs.leiden
    base: 2
    control_key: varm.healthy
  - _target_: grinch.GSEAPrerank.Config
    read_key: uns.kstest
    write_key: uns.gsea_hubmap
    gene_names_key: var.feature_name
    gene_sets: HuBMAP_ASCTplusB_augmented_2022
  - _target_: grinch.GSEAPrerank.Config
    read_key: uns.kstest
    write_key: uns.gsea_go
    gene_names_key: var.feature_name
    gene_sets: GO_Biological_Process_2023